# Game constants
FPS = 30 
WINDOWWIDTH = 800
WINDOWHEIGHT = 600
PLATFORM_WIDTH = 100
PLATFORM_GAP = 20

# Physics
GRAVITY = 2.0
PLATFORM_FRICTION = 0.7
AIR_FRICTION = 0.9
MAX_VELOCITY_Y = 60.0
MIN_VELOCITY_Y = -30.0
INITIAL_MOVE_FORCE = 2.0
PLATFORM_MOVE_FORCE = 7.0
AIR_MOVE_FORCE = 2.0
JUMP_FORCE = -30.0
FLY_FORCE = -2.0
FLY_TIME = 10.0
PLATFORM_SPEED = -8.0

# Platform type specific:
# Timer
TIMER_FRAMES = FPS



